---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Tutorial'
Parameters:
  KeyName:
    Description: 'Key Pair name'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: ******
  VPC:
    Description: 'Just select the one and only default VPC'
    Type: 'AWS::EC2::VPC::Id'
    Default: 'vpc-017ac47ad8c1******'
  Subnet:
    Description: 'Just select one of the available subnets'
    Type: 'AWS::EC2::Subnet::Id'
    Default: 'subnet-0d7aaaf50bd******'
  InstanceType:
    Description: Select one of the possible instance types'
    Type: String
    Default: 't2.micro'
    AllowedValues: ['t2.micro', 't2.small', 't2.medium']
Mappings:
  RegionMap:
    'us-east-2':
      AMI: 'ami-0ada6d94f39******'
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'My security group'
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/0'
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  VM:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: [!Ref SecurityGroup]
      SubnetId: !Ref Subnet
Outputs:
  PublicName:
    Value: !GetAtt 'VM.PublicDnsName'
    Description: 'Public name (connect via SSH as user ec2-user)'
